redis:
  restart: always
tty: true
  image: redis
stdin_open: true
pyapp:
  restart: always
tty: true
  image: 192.168.0.190:80/python-redis-demo:${Build_Number}
  links:
  - 'redis:'
stdin_open: true
pyapplb:
  ports:
  - ${Port_Number}:5000
  restart: always
tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
stdin_open: true~ 

